apiVersion: v1
kind: Pod
metadata:
 name: nginx
spec:
 containers:
   - image: nginx
     name: nginx
     ports:
       - containerPort: 80
         protocol: TCP
     readinessProbe:
       httpGet:
         path: /
         port: 80
       timeoutSeconds: 2
