apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    type: web-server

spec:
  containers:
    - name: nginx
      image: nginx
  resources:
    requests:
      memory: "1 Gi"
      cpu: 1
